ugexe/zef

- lib/Zef/App.pm6
- lib/Zef/Config.pm6
Functionality for connecting to zef.pm: search, login, register.
> Initial Zef server API functionality

- lib/Zef/App.pm6
This method is temporary until perl6 has a good Archive/Unarchive module available. Each file is sent individually, so while not ideal, will work fine until a better solution presents itself.
> pushes to server now work

- lib/Zef/Builder.pm6
- lib/Zef/Getter.pm6
- lib/Zef/Phase/Building.pm6
- lib/Zef/Phase/Getting.pm6
- lib/Zef/Phase/Reporting.pm6
- lib/Zef/Phase/Testing.pm6
- lib/Zef/Reporter.pm6
- lib/Zef/Tester.pm6
- t/zef-builder.t
- t/zef-getter.t
> Move the BUILD submethods from the base class to the Phase role

- META.info
- lib/Zef/Net/HTTP/Actions.pm6
- lib/Zef/Net/HTTP/Response.pm6
It is planned to build on this so the various custom
header rules will get built in as well. This is already
built into the grammar, but my understanding of how
to create actions at this point prevents me from
adding the full parse for now
> Use actions to generate kv header pairs

- README.pod
Please use whatever you like, discard the rest. Thanks!
> Some edits -- mostly case and punctuation.

- lib/Zef.pm6
- lib/Zef/Client.pm6
This splits the extraction portion of the fetch code out, but only
behind private methods (for now)
> Split fetch and extract out

- .appveyor.yml
- .travis.yml
- lib/Zef/CLI.pm6
- lib/Zef/Utils/URI.pm6
> Fix CLI path handling and exit codes

- lib/Zef/CLI.pm6
Previously only identities, not urls or file paths, would check
if they were installed prior to testing during `zef install ...`.
This adds logic to make the same checks for urls and paths.
> Check harder before testing

- lib/Zef/CLI.pm6
Will make it more useful for piping the results or saving them to a file
or doing other things with them
> Make zef list print ===> Found via to stderr not stdout

- lib/Zef/Service/TAP.pm6
https://irclog.perlgeek.de/perl6-dev/2017-05-19#i_14607954
> Fix duplicated "\n" in output

- lib/Zef/Config.pm6
This commit checks a list of path candidates, if XDG_CONFIG_HOME
is defined it checks that, otherwise $HOME/.config/zef.
If that file doesn't exist it checks the ones it checked previously.
I believe this is slightly faster now because it checks for the
file's existence before trying to parse it. It also will show
an specific error if the file doesn't exist versus if it doesn't
parse.
zef/issues/158
> Allow $HOME/.config/zef or XDG_CONFIG_HOME for config

- README.pod
Not that it matters, but still :D
> “nom” → “master”

- lib/Zef/Extract.pm6
- lib/Zef/Service/Shell/PowerShell/download.pm6
- lib/Zef/Service/Shell/PowerShell/unzip.pm6
- lib/Zef/Utils/URI.pm6
- resources/scripts/win32http.ps1
This is a little hacky, but for now this should cover the most general cases.
Resolves #204
> Fix homedir containing spaces

- README.pod
- lib/Zef/Build.pm6
- lib/Zef/CLI.pm6
- lib/Zef/Client.pm6
- lib/Zef/Extract.pm6
- lib/Zef/Fetch.pm6
- lib/Zef/Repository/Ecosystems.pm6
- lib/Zef/Repository/MetaCPAN.pm6
- lib/Zef/Test.pm6
- resources/config.json
Adds the following options (in seconds) and defaults:
--fetch-timeout=600
--extract-timeout=3600
--build-timeout=3600
--test-timeout=3600
Resolves #105
> Add timeout functionality to various phases

- README.pod
> Eliminates unintended markdown

- lib/Zef.pm6
- lib/Zef/CLI.pm6
- lib/Zef/Client.pm6
- lib/Zef/Distribution.pm6
- lib/Zef/Distribution/DependencySpecification.pm6
- t/distribution-depends-parsing.t
Implements support for dependencies in the form of `{"any": ["Foo", "Bar"]}`
> Dependency alternatives

- lib/Zef/Repository/Ecosystems.pm6
Searching for given distributions previous involved iterating over
every single distribution in the ecosystem to see if its name and
version parts matched. This adds indexing of distributions based on
their short name, so when making the actual query we can iterate
over only those distributions indexed on the short name of the
requested identity.
This brings an install of HTTP::UserAgent from 160s to less than
20s on the system I'm testing on.
> Index distributions by short name in ::Ecosystems

- lib/Zef/Repository.rakumod
The previous sorting logic abused grouping on a distributions name
which doesn't work so well with things like requiring two versions
of the same module. This change simplifies the sorting logic and
fixes the aforementioned issue by grouping on the `.as` value,
allowing e.g. Foo:ver<1> and Foo:ver<1.1+> to correctly be grouped
separately. And since those example dependencies may ultimately
resolve to the same distribution we also add a uniqueness filter
on the long name identity.
Resolves #382
> Fix erroneous deduplication of dependencies

- lib/Zef/Service/TAP.rakumod
This fixes the loading of the TAP module in Zef::Service::TAP
> Correctly load TAP module

- lib/Zef/Client.rakumod
When looking for distributions from CURIs we should use the public
apis.
> Use CURI api instead of impl details for list-installed

- .appveyor.yml
- .circleci/config.yml
- .travis.yml
- lib/Zef/Utils/URI.rakumod
- resources/config.json
- xt/repository.t
This should completely activate BackPan for Raku in zef
> Add REA to default config

- resources/config.json
As per https://github.com/Raku/problem-solving/blob/master/solutions/meta/sunsetting-p6c-cpan.md
> Enable REA, disable CPAN and p6c ecosystems by default

- lib/Zef/Repository/Ecosystems.rakumod
- lib/Zef/Repository/LocalCache.rakumod
> Use Str for missing uri value

- lib/Zef.rakumod
- lib/Zef/Repository.rakumod
> Avoid recreating repository plugin instances

- lib/Zef/CLI.rakumod
> Abort if a directory install target doesn't contain a META6.json

- lib/Zef/Service/Shell/curl.rakumod
- lib/Zef/Service/Shell/wget.rakumod
PowerShell has aliases for curl and wget that don't emulate the respective programs interface, instead just doing a powershell Invoke-WebRequest. This adds a .exe check to the probe for curl and wget when running on Windows, and uses program name with extension as appropriate.
> Explicitly use .exe extension for known Windows aliases

- lib/Zef/Service/Shell/DistributionBuilder.rakumod
Previously when invoking a Distribution::Builder:: we would pass in the (potentially) modified/resolved meta data via stdin. This was intended to avoid escaping issues with passing it on the command line. However, closing $*IN on macOS causes shell/run to fail unless such calls explicitly declare :!in. Since these builders are plugins (and thus we have no control over if/how run/shell get used), we should find a way to pass in that meta data without having to close stdin.
This modifies the Distribution::Builder plugin to pass the meta data in via temp file, which avoids having to slurp (and thus close) $*IN/stdin.
Fixes https://github.com/krunen/term-termios/issues/20
> Pass modified meta to dist builder via tmp file instead of stdin

- lib/Zef/Repository.rakumod
Previously we were creating a new supply for each ecosystem that was being updated, as well as only closing the stderr (and not stdout) supply. This updates this logic to match what we do in e.g. `Zef::Fetch` by reusing the same two supplies for every ecosystem as well as explicitly closing them both when we are done.
> Optimize use of Supply

- lib/Zef/Service/Shell/tar.rakumod
GNU tar will try to download remote files if they contain a colon. This works around that issue by prefixing the already-relative paths with './' as needed, as this causes the path to not be parsed as a remote file uri.
> Workaround gnu tar remote file feature
