lib/Zef/App.pm6
lib/Zef/Authority/P6C.pm6
lib/Zef/Net/HTTP/Client.pm6
lib/Zef/Net/HTTP/Request.pm6
lib/Zef/Test.pm6
lib/Zef/Test/Result.pm6

Allow a tap for stdout/stderr, and log
to $.output as well. Store all Zef::Test::Result
objects inside Zef::Test.results

Zef::Test(::Result) improvements

---

lib/Zef/App.pm6
lib/Zef/Builder.pm6
t/zef-builder.t

--async
Precompiles a modules provides source files in
parallel while maintaining the correct build order.
Next we need to tie in the same with `depends` and
then tie it all into the parallel testing when
doing a complete install.

parallel `provides` precompilation

---

lib/Zef/Utils/SystemInfo.pm6

cygx++ brings to attention in #65 that `Proc.run` and `Proc.shell` can cause encoding errors when reading from `.out`. A default encoding of `utf8` is normally applied, but since these instances are not shown to the user we will just use `latin-1` which will not error on invalid characters.
Other instances of `run` and `shell` will need a better solution, as their `.out` is output back to the terminal to be seen

Fix run/shell encoding error for non-utf8 output

---

META6.json
lib/Zef/Config.pm6

Makes zef work on [Arch](https://aur.archlinux.org/packages/zef).

fix resources/config.json for system installations

---

lib/Zef.pm6
lib/Zef/CLI.pm6
lib/Zef/Client.pm6
lib/Zef/ContentStorage/P6C.pm6
lib/Zef/Distribution/DependencySpecification.pm6
lib/Zef/Extract.pm6
lib/Zef/Fetch.pm6
lib/Zef/Shell/Test.pm6
lib/Zef/Shell/prove.pm6
lib/Zef/Shell/prove6.pm6
lib/Zef/Test.pm6

Moves all previous output to `$*OUT` and `$*ERR` in `Zef::Client` to `Zef::CLI`, where `Zef::Client` communicates back status updates to `Zef::CLI` and `Zef::CLI` can then decide what type of output is appropriate to display. This opens up the possibility of a `Zef::GUI` front end that uses `Zef::Client` the same as `Zef::CLI`

Supply based

---

META6.json
README.pod
lib/Zef.pm6
lib/Zef/CLI.pm6
lib/Zef/ContentStorage/Ecosystems.pm6
lib/Zef/ContentStorage/MetaCPAN.pm6
resources/config.json
t/00-load.t
xt/content-storage.t
xt/install.t

MetaCPAN support is now its own thing. This new cpan support uses
cpan itself using an index located in the Perl6-ecosystems repo
alongside the p6c repo

Add cpan support

---

lib/Zef/CLI.pm6

Add missing use statement for the module which declares the enum.

Fix "Function 'BEFORE' needs parens to avoid gobbling block"

---

lib/Zef/CLI.pm6

These all do the same thing now:
`zef --force install CSV::Parser`
`zef install --force CSV::Parser`
`zef install CSV::Parser --force`
Resolves #109

Allow named options after positionals for CLI

---

resources/config.json

Some modules that pass with perl5 prove may fail with this (HTTP::UserAgent and LWP::UserAgent were encountering this due to how it skipped tests based on a dynamically loaded module - both have been patched).
You can test this with `zef --/tap-harness install My::Module`, which disables the perl6 TAP::Harness and falls back to the perl5 prove

Default to Perl6 TAP::Harness for testing

---

lib/Zef/Fetch.pm6
lib/Zef/Repository/Ecosystems.pm6

* When a fetching backend can't be found to handle a url a more
helpful message is shown indicating the fetching backends that
failed as well as the fetching backends that are not enabled
or available (so if git is not installed `git` would be listed,
hopefully hinting to the user they need to install git)
* Improve mirror handling for Ecosystems so that if a mirror
fails OR the fetch process for a specific backend fails then
it will `note` the failure to fetch that mirror (due to previous
bullet point) and then attempt to fetch the next mirror.

Improve Fetch reporting and functionality

---

META6.json

This project has a LICENSE file, but the license of the project is not
designated in the META6.json file.

Add license field to META6.json

---

lib/Zef/Service/Shell/curl.pm6
lib/Zef/Service/Shell/wget.pm6
resources/config.json
resources/scripts/win32http.ps1

* Use Last-Modified-If'ish behavior for wget, curl, and the
powershell commandlet
* Prefer curl to wget (seems significantly faster)
This is the first step to speeding up auto-update. The next step
will be to only run auto-update every X hours (PRs welcome), since
the optimizations in this PR don't get around having to wait for
the http connect / header-response.

Optimize ecosystem fetching speed

---

lib/Zef/Distribution.pm6

Some of the details around BUILDALL have changed in recent versions of
rakudo for speed reasons.  Rather than adjusting our use of BUILDALL
here to handle the fact that it is now a multi, move over to using TWEAK
which seems to more-closely match what we are wanting to do here.
Without this change:
% perl6 -Ilib bin/zef install .
===SORRY!=== Error while compiling /Users/aeruder/proj/rakudobuild/zef/lib/Zef/Distribution.pm6 (Zef::Distribution)
Cannot have a multi candidate for 'BUILDALL' when an only method is also in the package 'Zef::Distribution'
at /Users/aeruder/proj/rakudobuild/zef/lib/Zef/Distribution.pm6 (Zef::Distribution):48

Zef::Distribution: move BUILDALL -> TWEAK

---

lib/Zef/CLI.pm6

This makes it easier to find things in the output,
and also makes it much more obvious if multiple versions
of the same dist are installed.

Sort "list" output

---

bin/zef

to run zef from project folder without using any interpreter before bin/zef

add shebang line add runable flag

---

lib/Zef/Client.pm6
lib/Zef/Distribution/DependencySpecification.pm6
lib/Zef/Identity.pm6
t/identity.t

Ignore dep specs that contain `:from<native>`, so that versions of zef with the yet-to-be-introduced functionality regarding native dependencies do not crash.

Ignore native depends

---

lib/Zef/CLI.pm6

Before, it was only finding the first file matched if there were
multiple with the same name.
Fixes #244

Fix zef locate with bin/ and resources/ file finding

---

lib/Zef/Client.pm6
lib/Zef/Identity.pm6
lib/Zef/Utils/FileSystem.pm6

For simple dependency lists authors can do "curl:from<native>" to
search for what rakudo thinks is "libcurl" for a given system, or
"curl:from<bin>" to do a `which` style lookup of a bin script.
These aren't very flexible ( how does one make :from<bin> also work
with :ver<...> for instance ) but will hopefully work to handle
simple tasks like filtering out non-windows-y stuff when running on
windows.

Allow is-installed to search for :from<native> and :from<bin>

---

lib/Zef/Client.pm6

A user today had an issue installing a module: http://colabti.org/irclogger/irclogger_log/perl6?date=2018-07-23#l933
The original error was `No such method 'IO' for invocant of type 'Any'` and it took some time to find out that the dist's meta file had an empty source URL `"source-url" : "",`
This PR makes the error a bit more helpful:
```
$ perl6 -Ilib bin/zef install SeqSplitter                                                                                                                                                                 
===> Searching for: SeqSplitter
Missing source URL in distribution
```

Add more useful error when dist is missing source-url

---

lib/Zef/Distribution/Local.pm6

HI,
I found that $*VM.platform-library-name adds "lib" prefix to the generated file when `$resources` starts with "libraries/" prefix.
Cheers,

Fix example for resources method

---

lib/Zef/Service/Shell/wget.pm6

BusyBox has its own version of wget which does not support the -N flag.
Fetching thus fails with that version. So we guard against that version
in the classic wget Fetcher and add another Fetcher that detects the
BusyBox version and does not use the -N flag.
This most prominently fixes zef on alpine linux which is most often used in docker containers.

Fix fetching in BusyBox environment

---

lib/Zef/CLI.pm6
lib/Zef/Repository/Ecosystems.pm6
lib/Zef/Repository/LocalCache.pm6

Allows e.g. zef install Foo --/update (to not auto-update anything)
and zef install Foo --/update=p6c (to not auto-update just p6c).
Also allows `--update` (to force an update for all ecosystems)
and `--update=p6c` (to force an update for a specific ecosystem).

Allow auto-update to be disabled on the command-line

---

lib/Zef/Distribution.pm6
lib/Zef/Distribution/DependencySpecification.pm6
lib/Zef/Identity.pm6
t/identity.t

Previously searching for a name of a module (not a distribution
name) any auth that would contain a < or > would cause any
matching to fail. This fixes the grammar to properly parse
such characters in an identity string, as well as changing
how identities are constructed for provides to avoid parsing
from a string (instead setting the attributes directly).
Resolves #327

Fix parsing of auths from identities containing < or >

---

README.pod

Rakudobrew has been renamed to Rakubrew, so adapt the documentation
accordingly.

Change Rakudobrew -> Rakubrew in README.md

---

lib/Zef/Fetch.pm6
lib/Zef/Repository/Ecosystems.pm6

Use a log message rather than dying, which causes the error message to be lost.
This is a hotfix for https://github.com/ugexe/zef/issues/338

Notify when backends are not configured

---

lib/Zef.pm6
lib/Zef/Service/Shell/prove.pm6

I left the `zrun` wrappers intact. I'd let some time pass before removing them in case it turns out we need them after all.
I tested this on Windows by installing Zef into a precompiled rakudo 2020.02.1 in `C:\data\rakudo 2020.02.1` and installing `OO::Monitors` afterwards.
Fixes #337

Fix Zef on Windows with a Rakudo located in a path with spaces

---

lib/Zef/Service/Shell/git.pm6

While we don't explicitly support this uri format, allowing it to work is simply a matter of passing the user-info along to the plugin.
Resolves #359

Correctly handle ssh-style git uris

---

README.pod

This is because the metacpan repository was removed in 6101ae5.
Therefore, using the `--metacpan` option to the `search` command causes
`zef` to error and print the usage information.  Removing the reference
from the docs will help avoid users mistakenly using the no longer
available option.

Remove references to metacpan in README

---

lib/Zef/Distribution.pm6
t/distribution-depends-parsing.t

Allows for build and test dependencies to be declared in the hash form of `depends`. If both fields are use then we combine them.

Add hash dependency parsing for test/build depends

---

lib/Zef/Client.pm6

We have always had a hard coded list of ignored modules that was compromised of the core module names. This gets rid of the hard coded list and dynamically creates an equivalent list.
Resolves #367

Dynamically determine what modules to ignore

---

lib/Zef/Client.pm6

This allows users to reuse the ::LocalCache module with different config provided paths

Don't override config provided cache path

---

lib/Zef/Repository/Ecosystems.pm6

Previously we used race to use multiple workers to grep through
a single ecosystems list of distributions. This removes the
concurrency, which results in a 30% reduction in runtime when
installing HTTP::UserAgent.

Remove unneeded concurrency to speed up dependency resolution

---

lib/Zef/Client.rakumod

This appears to have been accidentally removed in v0.10.0, and
was resulting in `zef build .` reporting build failures despite
the build working.
Resolves #389

Fix missing build-result during build phase

---

lib/Zef/Repository.rakumod

Previously this could give the error No such method 'as' for
invocant of type 'Any' such as when it failed to find a native
dependency that wasn't already installed. This change returns
the original behavior where zef presents a message telling the
user it cannot find the dependency and any suggestions it has.

Fix issue when no candidates are found

---

lib/Zef/Service/Shell/prove.rakumod

Don't use prove on Windows, as that fails when there are spaces in the
executables path.

Fix testing with prove with spaces in $*EXECUTABLE

---

lib/Zef/Client.rakumod
lib/Zef/Repository/Ecosystems.rakumod
lib/Zef/Repository/LocalCache.rakumod

When adding distributions to the local cache we previously would
e.g. extract the tar file to $cache-dir. However this can be
problematic because the extractors are not aware of the required
file structure of the $cache-dir. This can lead to consumers of
$cache-dir to do funny thing.
This also adds a check to the cache modules store method so that
it won't try to store something that is already stored in the cache.
Both of the above fix an issue where distributions in a tar archive
without a directory prefix in the archive file would lead to the
cache storing additionally copies of itself within itself.

Don't bypass interface by extracting into cache directory

---

lib/Zef/Repository.rakumod

When searching for a specific distribution it shouldn't matter
which backend it comes from, and hence `race` was originally used.
However this doesn't provide any benefit and comes at the cost of
reproduciblity. This changes the search code to use `hyper` instead
of `race` to maintain the backend order from the config such that
two runs will always draw from the same backend / ecosystem.

Maintain config order preference of ecosystems

---

.appveyor.yml
.circleci/config.yml
.travis.yml
lib/Zef/CLI.rakumod
lib/Zef/Repository.rakumod
lib/Zef/Repository/Ecosystems.rakumod

The documentation for Z:R.update stated the return value was likely to be removed in the future, and now it is so. This makes its behavior consistent with the interface for all the Z:R:*.update adapters.
This also makes the table output of `zef update` only occur when using --verbose or --debug. This makes `zef update` take ~2s and `zef update --verbose` take ~20s instead of both taking ~20s. The actual reason its so slow is because there isn't a way to count the number of distributions without creating the distribution objects first (which is hard to avoid since creating the object automatically greps out meta data that isnt valid in certain ways). Since having a low/no output for `zef update` makes sense anyway this can stand in as a workaround in the mean time.

Skip 'update' output table when not using elevated verbosity

---

lib/Zef/Client.rakumod

This doesn't actually enable anything new, but an installer plugin
should have access to the logger.

Pass logger along to installer

---

lib/Zef/CLI.rakumod
lib/Zef/Service/TAP.rakumod

The previous TAP plugin required capturing $*OUT/$*ERR from TAPs
output which complicated showing that data to the user (such as
prefixing each line with i.e. '[zef] ...'). This uses new changes
to TAP to integrate with stdout and stderr Suppliers, allowing
output to be handled similarly as most other plugins.
This also sets HARNESS_VERBOSITY if --debug is passed which will
e.g. show individual test results and not just the result of
individual files.

Support increased verbosity in TAP plugin

---

lib/Zef/Service/TAP.rakumod

In the future we will be able to give TAP a cwd, but for now return to using the original chdir code

Fix regression with not setting cwd for TAP plugin

---

lib/Zef/CLI.rakumod
lib/Zef/Config.rakumod

This adds a ZEF_INSTALL_TO env variable that sets the default value of --install-to, as well as ZEF_CONFIG_* for top level configuration keys.

Add more env variable configuration options

---

META6.json
README.md
lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod
lib/Zef/Distribution.rakumod
lib/Zef/Distribution/Local.rakumod
lib/Zef/Identity.rakumod
lib/Zef/Repository/Ecosystems.rakumod
lib/Zef/Repository/LocalCache.rakumod
t/distribution-depends-parsing.rakutest

This updates various Perl 6 references to use their Raku counterpart, as well as updating a few examples/references to be less out-of-date.

Modernize various references

---

lib/Zef/CLI.rakumod

This ensures what is shown by `zef info Some::Module` is what would be chosen when doing `zef install Some::Module`

Use find-candidates instead of search for 'zef info ...'

---

lib/Zef/Client.rakumod
lib/Zef/Distribution/Local.rakumod

This has been removed from rakudo for years, and zef has issued a warning when encountering these distributions for 5 years. This finally removes support entirely instead of just complaining loudly.
Resolves #492

Remove support for META.info files

---

lib/Zef.rakumod
lib/Zef/Build.rakumod
lib/Zef/Extract.rakumod
lib/Zef/Fetch.rakumod
lib/Zef/Install.rakumod
lib/Zef/Report.rakumod
lib/Zef/Service/FetchPath.rakumod
lib/Zef/Service/FileReporter.rakumod
lib/Zef/Service/InstallRakuDistribution.rakumod
lib/Zef/Service/Shell/DistributionBuilder.rakumod
lib/Zef/Service/Shell/LegacyBuild.rakumod
lib/Zef/Service/Shell/PowerShell/download.rakumod
lib/Zef/Service/Shell/PowerShell/unzip.rakumod
lib/Zef/Service/Shell/Test.rakumod
lib/Zef/Service/Shell/curl.rakumod
lib/Zef/Service/Shell/git.rakumod
lib/Zef/Service/Shell/p5tar.rakumod
lib/Zef/Service/Shell/prove.rakumod
lib/Zef/Service/Shell/tar.rakumod
lib/Zef/Service/Shell/unzip.rakumod
lib/Zef/Service/Shell/wget.rakumod
lib/Zef/Service/TAP.rakumod
lib/Zef/Test.rakumod

At one time the various plugins would be created anew for each use, but later on we started caching those instances. That change led to Supply reuse that showed itself as duplicate messages on any use of said plugin beyond the first.
This passes in the loggers through the function calls such that we can create new ones before we call the function. This avoids the Supply reuse issue mentioned earlier.
Fixes #496

Pass loggers through functions instead of initializing with object

---

lib/Zef/CLI.rakumod

This was useful when $?DISTRIBUTION was first added to rakudo so zef could start using it despite people on older rakudos using newer zef releases. We don't really need to support those old rakudos anymore, so this removes the EVAL.

Remove unneeded EVAL

---

lib/Zef/CLI.rakumod

The command has been advertised as --deps-only for a long time, so start telling users to use that instead of --depsonly.

Deprecate --depsonly

---

lib/Zef/Service/Shell/PowerShell.rakumod
lib/Zef/Service/Shell/curl.rakumod
lib/Zef/Service/Shell/git.rakumod
lib/Zef/Service/Shell/p5tar.rakumod
lib/Zef/Service/Shell/prove.rakumod
lib/Zef/Service/Shell/tar.rakumod
lib/Zef/Service/Shell/unzip.rakumod
lib/Zef/Service/Shell/wget.rakumod
lib/Zef/Service/TAP.rakumod

Previously various probe methods used `state`, which is not thread safe. Since we preload all the plugins it didn't need to be thread safe. This updates various probe methods to be thread safe despite the above comment only because it is technically more correct and potentially makes updating the plugin system a bit easier.

Make probe methods thread safe

---

lib/Zef.rakumod

Previously the plugin name would get shown with a +{anon} added to its name due to adding an anonymous role. That isn't useful for users to know, so this sets the name back to what it was prior to adding the anonymous role.

Cleanup plugin name output

---

.appveyor.yml
lib/Zef/Config.rakumod
resources/config.json

At one point we moved the temp directory zef used from `$*HOME/.zef/tmp` to `$*TMPDIR/.zef`. However, this meant the temp directories started to be the same for different users, and thus permissions issues could arise. This changes the temp directory to `$*TMPDIR/.zef/$time.$pid`, and adds the config logic for interpolating `{time}` and `$*PID`.
Fixes #510

Avoid permission issues with sharing $*TMPDIR with other users

---

META6.json

This adds the new zef IRC channel to it's META6.json support information.

Add IRC details

---

lib/Zef/Service/Shell/tar.rakumod

We only need to call out to tar once, but it looks like it started doing it twice accidently during a refactor. This fixes the probe to only call out to `tar --help` once.

Remove extra call to tar during probe

---

lib/Zef/Service/Shell/tar.rakumod

On OpenBSD the tar command does not support long options, nor does it support any form of `--help` type output. This removes usages of long options in favor of the equivalent short option, and special cases the OpenBSD tar detection logic based on the output of `tar` (instead of `tar --help` like other OS). These changes should allow `tar` to work as expected on OpenBSD.

Fix tar invocations on OpenBSD

---

META6.json
lib/Zef/Client.rakumod
t/00-load.rakutest
t/build.rakutest
t/distribution-depends-parsing.rakutest
t/extract.rakutest
t/fetch.rakutest
t/identity.rakutest
t/install.rakutest
t/repository.rakutest
t/test.rakutest
t/utils-filesystem.rakutest
xt/install.rakutest
xt/repository.rakutest

The core modules are no longer versions as e.g. 6.d, so checking for 6.c+ no longer makes sense. We could technically pin it on the 20XX.XX.X type versions rakudo is using, but that will require more consideration by myself (other compilers may not version them similarly, although they would have had to follow the original v6.c versioning), and commitment to a consistent versioning schema by Rakudo for its core modules.

Unpin core dependencies

---

lib/Zef.rakumod
lib/Zef/Build.rakumod
lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod
lib/Zef/Config.rakumod
lib/Zef/Distribution.rakumod
lib/Zef/Distribution/DependencySpecification.rakumod
lib/Zef/Distribution/Local.rakumod
lib/Zef/Extract.rakumod
lib/Zef/Fetch.rakumod
lib/Zef/Install.rakumod
lib/Zef/Report.rakumod
lib/Zef/Repository.rakumod
lib/Zef/Repository/Ecosystems.rakumod
lib/Zef/Repository/LocalCache.rakumod
lib/Zef/Service/FetchPath.rakumod
lib/Zef/Service/FileReporter.rakumod
lib/Zef/Service/InstallRakuDistribution.rakumod
lib/Zef/Service/Shell/DistributionBuilder.rakumod
lib/Zef/Service/Shell/LegacyBuild.rakumod
lib/Zef/Service/Shell/Test.rakumod
lib/Zef/Service/Shell/curl.rakumod
lib/Zef/Service/Shell/git.rakumod
lib/Zef/Service/Shell/prove.rakumod
lib/Zef/Service/Shell/tar.rakumod
lib/Zef/Service/Shell/unzip.rakumod
lib/Zef/Service/Shell/wget.rakumod
lib/Zef/Service/TAP.rakumod
lib/Zef/Test.rakumod

This ensures that when a zef module is loaded that it only imports other zef modules contained with the same distribution.
Note this implementation is a bit verbose and may not be worth cargo culting. There is a PR to rakudo that tries to do this same thing automatically for all distributions (although it needs to be revisited), and the pinning of `auth` is questionable (and may go away in the future). For now we'll see how well doing it the explicit way works out.

Ensure Zef modules all load the same version

---

lib/Zef.rakumod

The values of 'provides' meta data can be mutated by e.g. CURI and so checking for the string length of those values may not always be the best check. We are only interseted if the key exists, so this updates the code to only check for that.

Check for existence instead of number of characters

---

.appveyor.yml

The latest version of strawberry perl doesn't seem to want to install on appveyor, we we are pinning it to the last known working version.

Pin perl version

---

lib/Zef.rakumod
lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod
lib/Zef/Service/Shell/Test.rakumod
lib/Zef/Service/Shell/prove.rakumod
lib/Zef/Service/TAP.rakumod

Previously we always installed to a CURI. However, installing to a CURS means we can test + install while only compiling once. It isn't perfect though, as it doesn't work quite right with custom repository locations. This adds said staging workflow for installing to the default named repos.

Add staging to installation workflow

---

lib/Zef/CLI.rakumod
lib/Zef/Extract.rakumod
resources/config.json

Previously one could install a local distribution given it was already extracted into a folder, i.e. `zef install ./foo`. This allows installing from local archive files as well, i.e. `zef install ./foo.tar.gz`.

Allow installing local archive files

---

lib/Zef/Repository/LocalCache.rakumod

Previous the cache would store the absolute path in MANIFEST.zef (the index used for ::LocalCache). This makes it so we save and consume a relative path instead, allowing the it to be relocated without needing to update the index.

Make cache index relocatable

---

lib/Zef/CLI.rakumod
lib/Zef/Repository.rakumod
lib/Zef/Repository/Ecosystems.rakumod

All other parts of zef send output to stdout/stderr through a logging mechanism. The Repository (and Repository plugins) were the only plugins that were not already doing this. This updates the aforementioned Repository related code to using the idiomatic logging mechanism to send terminal output (specifically the output to tell the user when an ecosystem has been updated).

Avoid printing to stdout/stderr inside repository

---

lib/Zef.rakumod
lib/Zef/Build.rakumod
lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod
lib/Zef/Config.rakumod
lib/Zef/Distribution.rakumod
lib/Zef/Distribution/DependencySpecification.rakumod
lib/Zef/Distribution/Local.rakumod
lib/Zef/Extract.rakumod
lib/Zef/Fetch.rakumod
lib/Zef/Install.rakumod
lib/Zef/Report.rakumod
lib/Zef/Repository.rakumod
lib/Zef/Repository/Ecosystems.rakumod
lib/Zef/Repository/LocalCache.rakumod
lib/Zef/Service/FetchPath.rakumod
lib/Zef/Service/FileReporter.rakumod
lib/Zef/Service/InstallRakuDistribution.rakumod
lib/Zef/Service/Shell/DistributionBuilder.rakumod
lib/Zef/Service/Shell/LegacyBuild.rakumod
lib/Zef/Service/Shell/Test.rakumod
lib/Zef/Service/Shell/curl.rakumod
lib/Zef/Service/Shell/git.rakumod
lib/Zef/Service/Shell/prove.rakumod
lib/Zef/Service/Shell/tar.rakumod
lib/Zef/Service/Shell/unzip.rakumod
lib/Zef/Service/Shell/wget.rakumod
lib/Zef/Service/TAP.rakumod
lib/Zef/Test.rakumod

Zef tries to only load code from the version it was packaged with by doing `use Zef:ver($?DISTRIBUTION.meta<version>)`. However, some `CompUnit::Repository::Registry` return a `Distribution` that only has a `ver` (not `version`) field which would result in `use Zef:ver<>` which isn't a legal import statement. The adds a fallback to the `ver` field, as well as explicitly adding the Raku defaults for all import adverbs.

Use fallback versions in import statements

---

lib/Zef/Repository/Ecosystems.rakumod
lib/Zef/Repository/LocalCache.rakumod

Previously it was possible (although extremely unlikely) that a distribution could exist in an ecosystem without a name field, which could lead to warnings when we attempt to stringify it. A similar thing could also occur when an invalid long name is used in the provides field, such that we fail to parse the name. This ignores such distributions during the indexing process.
Fixes #543

Avoid warnings when ecosystem contains invalid distribution name

---

.appveyor.yml
.circleci/config.yml
README.md
lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod
lib/Zef/Install.rakumod
lib/Zef/Service/InstallRakuDistribution.rakumod

This adds a flag to disable precompilation done when installing to a CompUnit::Repository::Installation
Resolves #547

Add --/precompile-install flag

---

lib/Zef/Client.rakumod

This fixes a bug in the staging workflow that caused --dry to always exist unsuccessfully.

Fix dry installs not staging properly

---

lib/Zef/Config.rakumod

On macOS $*TMPDIR has a trailing / by default whereas on other OS it does not. This lead to zef output that would result in displaying paths with duplicated / like /tmp//foo/bar. This instead uses the absolute paths of those same objects which removes the unneeded trailing /

Normalize config path template variables

---

lib/Zef/CLI.rakumod

Previously there was no way to pass in arguments to zef via stdin, which can be useful for large argument lists or when piping from a list of modules. This updates zef to treat '-' for zef install and update to read the data from stdin and treat them as positional arguments.

Allow positional arguments passed in through STDIN via '-'

---

resources/config.json

Previously zef would use a temp directory like /tmp/.zef/[some-id], but that meant /tmp/.zef could be reused and thus have permissions for a different user. This updates zef to use a temp directory like /tmp/.zef.[some-id] such that subdirectory under /tmp will be created for each run and thus have permissions for the user running zef.
Resolves #563

Avoid reusing subdirectory in temp path

---

lib/Zef/CLI.rakumod

Previously when using `zef browse ...` with a distribution that does not have a "support" section in it's META6.json it would give an unhelpful error related to hash initialization. This fixes the issue by ensuring we have an empty hash.

Fix browse sub command error message

---

lib/Zef/Distribution.rakumod

in pre-RakuAST, sprintf is relatively expensive. There's `use v6.e.PREVIEW` + `zprintf` which is a drop-in replacement for sprintf that doesn't have to redo the format parsing step, but I thought adding something like that to zef wouldn't be welcome.
I could only test it on my machine which is currently doing a relatively big unrelated workload, so my timings are possibly very inexact, but the time to do `zef list > /dev/null` (only removing terminal overhead by not printing so much) went from roughly 30s to 14s.
I have not measured the difference for other parts of zef, like zef install or so. I don't expect them to gain very much speed tbh.

Micro-optimize Zef::Distribution!long-name

---

lib/Zef/Client.rakumod
lib/Zef/Extract.rakumod
lib/Zef/Service/Shell/DistributionBuilder.rakumod
lib/Zef/Service/Shell/LegacyBuild.rakumod
lib/Zef/Service/Shell/Test.rakumod
lib/Zef/Service/Shell/curl.rakumod
lib/Zef/Service/Shell/git.rakumod
lib/Zef/Service/Shell/tar.rakumod
lib/Zef/Service/Shell/unzip.rakumod
lib/Zef/Service/Shell/wget.rakumod

Zef uses the curl, tar, unzip, and git commands to do various things. It can be useful to know how zef is using these tools when debugging, but there was no way for users to know what exactly they can run to emulate the behavior. This adds extra output when running zef with `--debug` that shows what any command zef runs is.

Output commands run by Zef::Service::Shell::* wrappers

---

lib/Zef/CLI.rakumod
lib/Zef/Client.rakumod

Previously e.g. `zef depends Red` could fail for users that did not have the postgres native dependency installed. However, for that specific command it shouldn't matter if it can't resolve a native dependency because we don't look up transitive dependencies for them. Instead we could just list the native dependency and allow zef to continue finding other dependencies.
Fixes #517

Improve force-resolve behavior to accomodate `zef depends ...`

---

lib/Zef/Repository.rakumod

Calling a non existent method on Nil returns Nil, which means `%x{$foo.as}` does not work as expected if `$foo` happens to be Nil. This filters our Nils from search results to avoid the aforementioned issue.
Resolves #568

Avoid passing along Nils
